doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_sqlite'
        server_version: '3'
        charset: 'utf8mb4'

        # With Symfony 3.3, remove the `resolve:` prefix
        path: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
