vich_uploader:
    db_driver: orm

    mappings:
        files:
            upload_destination: '%kernel.project_dir%/files/'
            namer: vich_uploader.namer_origname
            directory_namer: App\Naming\FileSubdirectoryNamer
