vich_uploader:
    db_driver: orm

    mappings:
        files:
            upload_destination: '%kernel.project_dir%/%env(APP_FILES_DIRECTORY)%/'
            namer: vich_uploader.namer_origname
            directory_namer: app.vichuploader.directorynamer
